### ISSUE TITLE
Multiple "back to index" links seen

### ISSUE THREAD

**Issue by ayyelle** [earthgrazer/codereviewer#4] opened 2016-04-14 00:40 UTC
Only in the sample where there is a "file diff", there is only one "back to index" link where there is no "file diff".

**Comment by earthgrazer** [comment] 2016-04-14 04:43
Caused by empty review files added when user clicks "add file" button without filling in the new file. Fixed by filtering out empty review files in ReviewManagementService.

**Closed as completed by earthgrazer** 2016-04-14 04:43 UTC
Labels: bug
